exclude: ".venv|__pycache__|tests/dev/|tests/fixtures/"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=500
      - id: check-case-conflict
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.2"
    hooks:
      - id: ruff
        args:
          - --fix
          - --exit-non-zero-on-fix
          - --target-version=py39
        types_or:
          - python
          - pyi
      - id: ruff-format
        args:
          - --target-version=py39
        types_or:
          - python
          - pyi


  # Disabled until PyQt translation support f-strings
  # - repo: https://github.com/asottile/pyupgrade
  #   rev: v3.15.0
  #   hooks:
  #     - id: pyupgrade
  #       args:
  #         - "--py39-plus"


ci:
    autoupdate_schedule: quarterly
    skip: []
    submodules: false
